/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: btn_edit                                              *
* Dimensions:  24 * 24                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsbtn_edit[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palbtn_edit = {
  2,   /* number of entries */
  0,    /* No transparency */
  &Colorsbtn_edit[0]
};

static GUI_CONST_STORAGE unsigned char acbtn_edit[] = {
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ______XX, ________,
  ________, _____XXX, X_______,
  ________, ____XXXX, XX______,
  ________, ___XXXXX, XX______,
  ________, __XXXXXX, X_______,
  ________, _XXXXXXX, ________,
  ________, XXXXXXX_, ________,
  ________, XXXXXX__, ________,
  _______X, _XXXX___, ________,
  _______X, X_XX____, ________,
  ______XX, XX______, ________,
  ______XX, ________, ________,
  ________, ________, ________,
  _____XXX, XXXXXXXX, XX______,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmbtn_edit = {
  24, /* XSize */
  24, /* YSize */
  3, /* BytesPerLine */
  1, /* BitsPerPixel */
  acbtn_edit,  /* Pointer to picture data (indices) */
  &Palbtn_edit  /* Pointer to palette */
};

/* *** End of file *** */
