/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ic_fbmessenger                                        *
* Dimensions:  16 * 16                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsic_fbmessenger[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palic_fbmessenger = {
  2,    /* number of entries */
  0,     /* No transparency */
  &Colorsic_fbmessenger[0]
};

static GUI_CONST_STORAGE unsigned char acic_fbmessenger[] = {
  XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX,
  XXXXX___, ___XXXXX,
  XXX_____, _____XXX,
  XX______, ______XX,
  XX______, _______X,
  X_____XX, ___X___X,
  _____XXX, X_XX____,
  ____XX__, XXX_____,
  X___X___, XX_____X,
  XX______, ______XX,
  XXX_____, _____XXX,
  XXXX____, ___XXXXX,
  XXXX__XX, XXXXXXXX,
  XXXX_XXX, XXXXXXXX,
  XXXX_XXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmic_fbmessenger = {
  16, /* XSize */
  16, /* YSize */
  2, /* BytesPerLine */
  1, /* BitsPerPixel */
  acic_fbmessenger,  /* Pointer to picture data (indices) */
  &Palic_fbmessenger  /* Pointer to palette */
};

/* *** End of file *** */
