/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ic_up                                                 *
* Dimensions:  17 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsic_up[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palic_up = {
  2,    /* number of entries */
  0,    /* No transparency */
  &Colorsic_up[0]
};

static GUI_CONST_STORAGE unsigned char acic_up[] = {
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, X_______, ________,
  _______X, XX______, ________,
  ______XX, XXX_____, ________,
  _____XXX, XXXX____, ________,
  ____XXXX, XXXXX___, ________,
  ___XXXXX, XXXXXX__, ________,
  __XXXXXX, XXXXXXX_, ________,
  ______XX, XXX_____, ________,
  ______XX, XXX_____, ________,
  ______XX, XXX_____, ________,
  ______XX, XXX_____, ________,
  ______XX, XXX_____, ________,
  ______XX, XXX_____, ________,
  ______XX, XXX_____, ________,
  ________, ________, ________,
  ______XX, XXX_____, ________,
  ______XX, XXX_____, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________,
  ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmic_up = {
  17, /* XSize */
  32, /* YSize */
  3, /* BytesPerLine */
  1, /* BitsPerPixel */
  acic_up,  /* Pointer to picture data (indices) */
  &Palic_up  /* Pointer to palette */
};

/* *** End of file *** */
