/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_whatsapp                                          *
* Dimensions:  16 * 16                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_whatsapp[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_whatsapp = {
  2,   /* number of entries */
  0,    /* No transparency */
  &Colorsico_whatsapp[0]
};

static GUI_CONST_STORAGE unsigned char acico_whatsapp[] = {
  XXXXXXXX, XXXXXXXX,
  XXXXXXX_, __XXXXXX,
  XXXX___X, ____XXXX,
  XXX___XX, XXX___XX,
  XXX__XXX, XXXX__XX,
  XX__X__X, XXXXX__X,
  X__XX__X, XXXXX__X,
  X__XX___, XXXXXX_X,
  X__XX___, XXXXXX__,
  XX_XXX__, ____X__X,
  X___XXX_, ____X__X,
  XX__XXXX, XX_XX__X,
  XX_XXXXX, XXX___XX,
  XX_____X, _____XXX,
  X_______, ___XXXXX,
  XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmico_whatsapp = {
  16, /* XSize */
  16, /* YSize */
  2, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_whatsapp,  /* Pointer to picture data (indices) */
  &Palico_whatsapp  /* Pointer to palette */
};

/* *** End of file *** */
