/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_content_steps                                     *
* Dimensions:  16 * 16                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_content_steps[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_content_steps = {
  2,        /* number of entries */
  0,         /* No transparency */
  &Colorsico_content_steps[0]
};

static GUI_CONST_STORAGE unsigned char acico_content_steps[] = {
  ________, ________,
  ________, __XXXX__,
  ________, _XXXXX__,
  ________, _XXXXXX_,
  ___XXX__, _XXXXXX_,
  __XXXXX_, __XXXXX_,
  _XXXXXX_, __XXXX__,
  _XXXXXX_, ___XXX__,
  _XXXXXX_, ________,
  _XXXXX__, ___XXX__,
  __XXX___, ___XXX__,
  __XXX___, ________,
  ________, ________,
  __XXX___, ________,
  __XXX___, ________,
  ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_content_steps = {
  16, /* XSize */
  16, /* YSize */
  2, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_content_steps,  /* Pointer to picture data (indices) */
  &Palico_content_steps  /* Pointer to palette */
};

/* *** End of file *** */
