/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_B                                                 *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_B[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_B = {
  2,        /* number of entries */
  0,         /* No transparency */
  &Colorsico_B[0]
};

static GUI_CONST_STORAGE unsigned char acico_B[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, __XXXXXX, XXXXXXX_, ________, ________, ________,
  ________, ________, ________, __XXXXXX, XXXXXXX_, ________, ________, ________,
  ________, ________, ________, ____XXXX, XXXXX___, ________, ________, ________,
  ________, ________, ________, ____XXXX, XXXXX___, ________, ________, ________,
  ________, ________, ________, ______XX, XXX_____, ________, ________, ________,
  ________, ________, ________, ______XX, XXX_____, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_B = {
  64, /* XSize */
  64, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_B,  /* Pointer to picture data (indices) */
  &Palico_B  /* Pointer to palette */
};

/* *** End of file *** */
