/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_lvup                                              *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_lvup[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_lvup = {
  2,    /* number of entries */
  0,     /* No transparency */
  &Colorsico_lvup[0]
};

static GUI_CONST_STORAGE unsigned char acico_lvup[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XX___X__, _XXXXXX_, _XXXXXXX, X___XXXX, ___XXX__, _X____XX, XXXXXX__,
  ___XXXXX, XX___XX_, __XXXX__, XXXXXXXX, X___XXXX, ___XXX__, _______X, XXXXXX__,
  ___XXXXX, XX___XX_, __XXXX__, XXXXXXXX, X___XXXX, ___XXX__, __XX____, XXXXXX__,
  ___XXXXX, XX___XXX, __XXXX__, XXXXXXXX, X___XXXX, ___XXX__, _XXXX___, XXXXXX__,
  ___XXXXX, XX___XXX, ___XX__X, XXXXXXXX, X___XXXX, ___XXX__, _XXXX___, XXXXXX__,
  ___XXXXX, XX___XXX, ___XX__X, XXXXXXXX, X___XXXX, ___XXX__, _XXXX___, XXXXXX__,
  ___XXXXX, XX___XXX, X__XX__X, XXXXXXXX, X___XXXX, ___XXX__, _XXXX___, XXXXXX__,
  ___XXXXX, XX___XXX, X_____XX, XXXXXXXX, X___XXXX, ___XXX__, _XXXX___, XXXXXX__,
  ___XXXXX, XX___XXX, X_____XX, XXXXXXXX, X___XXX_, ___XXX__, __XX____, XXXXXX__,
  ___XXXXX, XX___XXX, XX___XXX, XXXXXXXX, X_______, ___XXX__, _______X, XXXXXX__,
  ___XXXXX, XX___XXX, XX___XXX, XXXXXXXX, XX_____X, ___XXX__, _X____XX, XXXXXX__,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXX__,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXX__,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXX__,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXXXX, XXXXXX__,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  ________, _______X, XXX_____, ________, ________, ________, ________, ________,
  ________, ________, XXX_____, ________, ________, ________, ________, ________,
  ________, ________, XXXX____, ________, ________, XXX_____, ________, ________,
  ________, ________, _XXX____, ________, _______X, XXXX____, ________, ________,
  ________, ________, __XX____, ________, _______X, X_XXX___, ________, ________,
  ________, ________, ___XX___, ________, ______XX, X_XXX___, ________, ________,
  ________, ________, ____X___, ________, ______XX, X__XXX__, ________, ________,
  ________, ________, ________, ________, ______XX, X___XXX_, ________, ________,
  ________, ________, ________, ________, _______X, X___XXX_, ________, ________,
  ________, ________, ________, ________, _______X, XX___XXX, ________, ________,
  ________, ________, ________, ________, ________, XXX___XX, X_______, ________,
  ________, ________, ________, ________, ________, _XXX___X, XX______, ________,
  ________, ________, ________, ________, _XXXXXXX, XXXX____, XXXXXXXX, XXXXX___,
  ________, ________, ________, ________, XXXXXXXX, XXXXX___, XXXXXXXX, XXXXX___,
  ________, ________, ________, _______X, XX______, ________, _XXXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, __XXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, __XXX___, ___XX___,
  ________, ________, ________, ________, XXX_____, ________, __XXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, __XXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, __XXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, __XXX___, ___XX___,
  ________, ________, ________, ________, XXX_____, ________, __XXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, __XXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, __XXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, __XXX___, ___XX___,
  ________, ________, ________, ________, XXX_____, ________, __XXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, _XXXX___, ___XX___,
  ________, ________, ________, _______X, XX______, ________, XXXXXXXX, XXXXX___,
  ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XX_XXXXX, XXXXX___,
  ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_lvup = {
  64, /* XSize */
  64, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_lvup,  /* Pointer to picture data (indices) */
  &Palico_lvup  /* Pointer to palette */
};

/* *** End of file *** */
