/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_notice                                            *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_notice[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_notice = {
  2,    /* number of entries */
  0,    /* No transparency */
  &Colorsico_notice[0]
};

static GUI_CONST_STORAGE unsigned char acico_notice[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, _XX_____, ________, ________, ________, ________, ________,
  ________, ________, XXXX____, ________, ________, ________, ________, ________,
  ________, ________, XXXXX___, ________, ________, ________, ________, ________,
  ________, ________, _XXXXX__, ________, ________, ________, ________, ________,
  ________, ________, __XXXXX_, ________, ________, ________, ________, ________,
  ________, ________, ___XXXXX, ________, __XX____, ________, ________, ________,
  ________, ________, ____XXXX, X_______, __XXX___, ________, ________, ________,
  ________, ________, _____XXX, XX______, _XXXXX__, ________, ________, ________,
  ________, ________, ______XX, XXX_____, _XXXXXX_, ________, ________, ________,
  ________, ________, _______X, XXXX____, _XXXXXXX, ________, ________, ________,
  ________, ________, ________, XXXXX___, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, _XXXXX__, XXXX_XXX, XX______, ________, ________,
  ________, ________, ________, __XXXXX_, XXXX__XX, XXX_____, ________, ________,
  ________, ________, ________, ___XXXXX, XXXX___X, XXXX____, ________, ________,
  ________, ________, ________, ____XXXX, XXX_____, XXXXX___, __XX____, ________,
  _______X, XXXXXXXX, XXXX____, _____XXX, XXX_____, _XXXXX__, _XXX____, ________,
  _______X, XXXXXXXX, XXXX____, ______XX, XXX_____, __XXXXX_, XXXXX___, ________,
  _______X, XXXXXXXX, XXXX____, _______X, XX______, ___XXXXX, XXXXX___, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, ____XXXX, XXXXXX__, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, _____XXX, XXXXXX__, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, _____XXX, XXXXXX__, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, ____XXXX, XXXXXXX_, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, ___XXXXX, XXXXXXX_, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, ___XXXXX, XXXXXXX_, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, _______X, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, ________, ____XXXX, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, ________, ________, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ________, ________, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  _______X, XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_notice = {
  64, /* XSize */
  64, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_notice,  /* Pointer to picture data (indices) */
  &Palico_notice  /* Pointer to palette */
};

/* *** End of file *** */
