/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_content_heart_w                                   *
* Dimensions:  32 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_content_heart_w[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_content_heart_w = {
  2,        /* number of entries */
  0,         /* No transparency */
  &Colorsico_content_heart_w[0]
};

static GUI_CONST_STORAGE unsigned char acico_content_heart_w[] = {
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  _______X, XXXXX___, ____XXXX, X_______,
  ______XX, XXXXXX__, ___XXXXX, XXX_____,
  _____XXX, XXXXXXX_, __XXXXXX, XXXX____,
  ____XXXX, XXXXXXXX, _XXXXXXX, XXXXX___,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXX____,
  _____XXX, XXXXXXXX, XXXXXXXX, XXXX____,
  ______XX, XXXXXXXX, XXXXXXXX, XXX_____,
  _______X, XXXXXXXX, XXXXXXXX, XX______,
  ________, XXXXXXXX, XXXXXXXX, X_______,
  ________, _XXXXXXX, XXXXXXXX, ________,
  ________, __XXXXXX, XXXXXXX_, ________,
  ________, ___XXXXX, XXXXXX__, ________,
  ________, ____XXXX, XXXXX___, ________,
  ________, _____XXX, XXXX____, ________,
  ________, ______XX, XXX_____, ________,
  ________, _______X, XX______, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_content_heart_w = {
  32, /* XSize */
  32, /* YSize */
  4, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_content_heart_w,  /* Pointer to picture data (indices) */
  &Palico_content_heart_w  /* Pointer to palette */
};

/* *** End of file *** */
