/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_trophy64                                          *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_trophy64[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_trophy64 = {
  2,        /* number of entries */
  0,         /* No transparency */
  &Colorsico_trophy64[0]
};

static GUI_CONST_STORAGE unsigned char acico_trophy64[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXX_, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXX_, ________, ________, ____XXXX, XXXX____, ________,
  ________, _______X, XXXXXXX_, ________, ________, ____XXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, X_______, ________, __XXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, XX______, ________, _XXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, XX______, ________, _XXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, XXXX____, _______X, XXXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, XXXX____, ________, XXXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, XX______, _X______, _XXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, X_____XX, XXXXX___, __XXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, X_____XX, XXXXXX__, __XXXXXX, XXXX____, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ________, ________, __XXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, ____XXXX, XXXXXXXX, ________, ________, ________,
  ________, ________, ________, ____XXXX, XXXXXXX_, ________, ________, ________,
  ________, ________, ________, _____XXX, XXXXXX__, ________, ________, ________,
  ________, ________, ________, _______X, XXXX____, ________, ________, ________,
  ________, ________, ________, _______X, XXXX____, ________, ________, ________,
  ________, ________, ________, _______X, XXXX____, ________, ________, ________,
  ________, ________, ________, _______X, XXXX____, ________, ________, ________,
  ________, ________, ________, _______X, XXXX____, ________, ________, ________,
  ________, ________, ________, _____XXX, XXXXXX__, ________, ________, ________,
  ________, ________, ________, ____XXXX, XXXXXXX_, ________, ________, ________,
  ________, ________, ________, ____XXXX, XXXXXXXX, ________, ________, ________,
  ________, ________, ________, __XXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, __XXXXXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_trophy64 = {
  64, /* XSize */
  64, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_trophy64,  /* Pointer to picture data (indices) */
  &Palico_trophy64  /* Pointer to palette */
};

/* *** End of file *** */
