/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_trophy32                                          *
* Dimensions:  32 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_trophy32[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_trophy32 = {
  2,        /* number of entries */
  0,         /* No transparency */
  &Colorsico_trophy32[0]
};

static GUI_CONST_STORAGE unsigned char acico_trophy32[] = {
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_,
  _____XXX, XXXXXXXX, __XXXXXX, XXXXX___,
  _____XXX, XXXXXXX_, ___XXXXX, XXXXX___,
  _____XXX, XXXXXX__, ____XXXX, XXXXX___,
  _____XXX, XXX_____, ________, XXXXX___,
  _____XXX, XXXX____, _______X, XXXXX___,
  _____XXX, XXXXX___, ______XX, XXXXX___,
  _____XXX, XXXXX___, _____XXX, XXXXX___,
  _____XXX, XXXX____, _X____XX, XXXXX___,
  _____XXX, XXXX___X, XXXX___X, XXXXX___,
  ______XX, XXXXXXXX, XXXXXXXX, XXXX____,
  _______X, XXXXXXXX, XXXXXXXX, XXX_____,
  ________, XXXXXXXX, XXXXXXXX, XX______,
  ________, _XXXXXXX, XXXXXXXX, X_______,
  ________, __XXXXXX, XXXXXXXX, ________,
  ________, ___XXXXX, XXXXXXX_, ________,
  ________, ____XXXX, XXXXXX__, ________,
  ________, _____XXX, XXXXX___, ________,
  ________, ______XX, XXXX____, ________,
  ________, _______X, XXX_____, ________,
  ________, _______X, XXX_____, ________,
  ________, _______X, XXX_____, ________,
  ________, ______XX, XXXX____, ________,
  ________, _____XXX, XXXXX___, ________,
  ________, ____XXXX, XXXXXX__, ________,
  ________, ___XXXXX, XXXXXXX_, ________,
  ________, __XXXXXX, XXXXXXXX, ________,
  ________, XXXXXXXX, XXXXXXXX, XX______,
  ________, XXXXXXXX, XXXXXXXX, XX______
};

GUI_CONST_STORAGE GUI_BITMAP bmico_trophy32 = {
  32, /* XSize */
  32, /* YSize */
  4, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_trophy32,  /* Pointer to picture data (indices) */
  &Palico_trophy32  /* Pointer to palette */
};

/* *** End of file *** */
