/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_time                                              *
* Dimensions:  32 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_time[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_time = {
  2,   /* number of entries */
  0,    /* No transparency */
  &Colorsico_time[0]
};

static GUI_CONST_STORAGE unsigned char acico_time[] = {
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ____XXXX, XXXX____, ________,
  ________, __XXXXXX, XXXXXX__, ________,
  ________, _XXXXXXX, XXXXXXX_, ________,
  ________, XXXX____, ____XXXX, ________,
  _______X, XXX_____, _____XXX, X_______,
  ______XX, XX_____X, X_____XX, XX______,
  ______XX, X______X, X______X, XX______,
  _____XXX, _______X, X_______, XXX_____,
  _____XXX, _______X, X_______, XXX_____,
  _____XXX, _______X, X_______, XXX_____,
  _____XXX, _______X, X_______, XXX_____,
  _____XXX, _______X, XX______, XXX_____,
  _____XXX, ________, XXX_____, XXX_____,
  _____XXX, ________, _XXX____, XXX_____,
  _____XXX, ________, __XXX___, XXX_____,
  ______XX, X_______, _______X, XX______,
  ______XX, XX______, ______XX, XX______,
  _______X, XXX_____, _____XXX, X_______,
  ________, XXXX____, ____XXXX, ________,
  ________, _XXXXXXX, XXXXXXX_, ________,
  ________, __XXXXXX, XXXXXX__, ________,
  ________, ____XXXX, XXXX____, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_time = {
  32, /* XSize */
  32, /* YSize */
  4, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_time,  /* Pointer to picture data (indices) */
  &Palico_time  /* Pointer to palette */
};

/* *** End of file *** */
