/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_sleep                                             *
* Dimensions:  32 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_sleep[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_sleep = {
  2,   /* number of entries */
  0,    /* No transparency */
  &Colorsico_sleep[0]
};

static GUI_CONST_STORAGE unsigned char acico_sleep[] = {
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, _______X, XXXX____, ________,
  ________, ____XXXX, XXXXX___, ________,
  ________, __XXXXXX, XXXXX___, ________,
  ________, _XXXXXXX, XXX_____, ________,
  ________, XXXXXXXX, XX______, ________,
  _______X, XXXXXXXX, X_______, ________,
  ______XX, XXXXXXXX, ________, ________,
  ______XX, XXXXXXXX, ________, ________,
  _____XXX, XXXXXXXX, ________, ________,
  _____XXX, XXXXXXX_, ________, ________,
  _____XXX, XXXXXXX_, ________, ________,
  _____XXX, XXXXXXX_, ________, ________,
  _____XXX, XXXXXXXX, ________, ________,
  _____XXX, XXXXXXXX, ________, ________,
  _____XXX, XXXXXXXX, X_______, ________,
  _____XXX, XXXXXXXX, X_______, ________,
  _____XXX, XXXXXXXX, XXX_____, ___X____,
  _____XXX, XXXXXXXX, XXXXX___, _XXXX___,
  ______XX, XXXXXXXX, XXXXXXXX, XXXX____,
  ______XX, XXXXXXXX, XXXXXXXX, XXXX____,
  _______X, XXXXXXXX, XXXXXXXX, XXX_____,
  ________, XXXXXXXX, XXXXXXXX, XX______,
  ________, _XXXXXXX, XXXXXXXX, X_______,
  ________, __XXXXXX, XXXXXXXX, ________,
  ________, ____XXXX, XXXXXX__, ________,
  ________, ________, XXX_____, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_sleep = {
  32, /* XSize */
  32, /* YSize */
  4, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_sleep,  /* Pointer to picture data (indices) */
  &Palico_sleep  /* Pointer to palette */
};

/* *** End of file *** */
