/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_pace_32                                           *
* Dimensions:  32 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_pace_32[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_pace_32 = {
  2,   /* number of entries */
  0,    /* No transparency */
  &Colorsico_pace_32[0]
};

static GUI_CONST_STORAGE unsigned char acico_pace_32[] = {
  ________, ________, ________, ________,
  ________, ________, ________, ________,
  ________, ________, ______XX, ________,
  ________, ________, _____XXX, X_______,
  ________, ________, _____XXX, X_______,
  ________, ________, _____XXX, X_______,
  ________, ________, ______XX, ________,
  ________, _______X, XXXXX___, ________,
  ________, ____XXXX, XXXXXXX_, ________,
  ________, ____XXXX, XXXXXXX_, ________,
  ________, ___XXX__, _XXXXXX_, ________,
  ________, ___XX___, XXXXXXXX, ________,
  ________, ___XX__X, XXXXXXXX, ________,
  ________, ___X___X, XXXXXXXX, ________,
  ________, ___X__XX, XXXX__XX, X_______,
  ________, _____XXX, XXXX___X, XXX_____,
  ________, _____XXX, XXX_____, _XXX____,
  ________, ____XXXX, XXX_____, __XXX___,
  ________, ____XXXX, XX______, ________,
  ________, ____XXXX, XX______, ________,
  ________, ____XXXX, XX_X____, ________,
  ________, ____XXXX, X__XX___, ________,
  ________, ____XXXX, X_XXXX__, ________,
  ________, ____XXXX, X_XXXXXX, ________,
  _______X, XXXXXXXX, X__XXXXX, ________,
  _______X, XXXXXXXX, _____XXX, X_______,
  ________, ___XXXX_, ______XX, X_______,
  ________, ________, ______XX, X_______,
  ________, ________, _______X, X_______,
  ________, ________, _______X, X_______,
  ________, ________, _______X, X_______,
  ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_pace_32 = {
  32, /* XSize */
  32, /* YSize */
  4, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_pace_32,  /* Pointer to picture data (indices) */
  &Palico_pace_32  /* Pointer to palette */
};

/* *** End of file *** */
