/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_takeeasy                                          *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_takeeasy[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_takeeasy = {
  2,        /* number of entries */
  0,         /* No transparency */
  &Colorsico_takeeasy[0]
};

static GUI_CONST_STORAGE unsigned char acico_takeeasy[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  _______X, XX_XXX__, ________, ________, ________, ________, ________, ________,
  _______X, XX_XXX__, ________, ________, ________, ________, ________, ________,
  ______XX, X_XXX___, ________, ________, ________, ________, ________, ________,
  ______XX, X_XXX___, ________, ________, ________, ________, ________, ________,
  ______XX, X_XXX___, ________, ______XX, XXXXXXXX, XXX_____, ________, ________,
  ______XX, X_XXX___, ________, ______XX, XXXXXXXX, XXX_____, ________, ________,
  ______XX, X_XXX___, ________, __XXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ______XX, X_XXX___, ________, __XXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ____XXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ____XXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  __XXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  __XXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, X___XXXX, XXXXX_XX, XXXXXXXX, X_XXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, X___XXXX, XXXXX_XX, XXXXXXXX, X_XXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, X_XXXXXX, XXX_XXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, X_XXXXXX, XXX_XXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, X_______,
  __XXXXXX, XXXXXXXX, X_XXXXXX, X_XXXXXX, XXXXXXXX, XXXXX_XX, XXXXXXXX, X_______,
  __XXXXXX, XXXXXXXX, X_XXXXXX, X_XXXXXX, XXXXXXXX, XXXXX_XX, XXXXXXXX, X_______,
  ____XXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXX___XX, XXXXX_XX, XXXXXXXX, XXX_____,
  ____XXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXX___XX, XXXXX_XX, XXXXXXXX, XXX_____,
  ____XXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, X_XXXXX_, XXXXX_XX, XXXXXXXX, XXX_____,
  ____XXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, X_XXXXX_, XXXXX_XX, XXXXXXXX, XXX_____,
  ______XX, XXXXXXXX, XXXXXXX_, XXXXXXX_, XXXXXXX_, XXXXX_XX, XXXXXXXX, XXX_____,
  ______XX, XXXXXXXX, XXXXXXX_, XXXXXXX_, XXXXXXX_, XXXXX_XX, XXXXXXXX, XXX_____,
  ______XX, XXXXXXXX, XXXXXXX_, XXXXXXX_, XXXXX_XX, XXXXX_XX, XXXXXXXX, XXX_____,
  ______XX, XXXXXXXX, XXXXXXX_, XXXXXXX_, XXXXX_XX, XXXXX_XX, XXXXXXXX, XXX_____,
  ______XX, XXXXXXXX, XXXXXXXX, X_XXXXX_, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXX_____,
  ______XX, XXXXXXXX, XXXXXXXX, X_XXXXX_, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXX_____,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, X_XXXXXX, XXXXXXXX, XXX_____,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, X_XXXXXX, XXXXXXXX, XXX_____,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, X_______,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, X_______,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmico_takeeasy = {
  64, /* XSize */
  64, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_takeeasy,  /* Pointer to picture data (indices) */
  &Palico_takeeasy  /* Pointer to palette */
};

/* *** End of file *** */
