/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_footer_pagemark_n                                 *
* Dimensions:  6 * 6                                                 *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_footer_pagemark_n[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_footer_pagemark_n = {
  2,        /* number of entries */
  0,         /* No transparency */
  &Colorsico_footer_pagemark_n[0]
};

static GUI_CONST_STORAGE unsigned char acico_footer_pagemark_n[] = {
  ________,
  ________,
  _XXXX___,
  _X__X___,
  _X__X___,
  _XXXX___
};

GUI_CONST_STORAGE GUI_BITMAP bmico_footer_pagemark_n = {
  6, /* XSize */
  6, /* YSize */
  1, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_footer_pagemark_n,  /* Pointer to picture data (indices) */
  &Palico_footer_pagemark_n  /* Pointer to palette */
};

/* *** End of file *** */
