/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_updating                                          *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_updating[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_updating = {
  2,   /* number of entries */
  0,    /* No transparency */
  &Colorsico_updating[0]
};

static GUI_CONST_STORAGE unsigned char acico_updating[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ______XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, ______XX, XX______, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, __XXXXXX, XXXXXXX_, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXXXX, X_______, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, _XXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX,
  XXXXXXXX, XX______, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX, ______XX, XXXXXXXX,
  XXXXXXXX, XX______, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, X______X, XXXXXXXX,
  XXXXXXXX, X______X, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, X______X, XXXXXXXX,
  XXXXXXXX, X_____XX, XXXXXXXX, XXXX____, _____XXX, XXXXXXXX, XX______, XXXXXXXX,
  XXXXXXXX, ______XX, XXXXXXXX, XXX_____, ______XX, XXXXXXXX, XXX_____, XXXXXXXX,
  XXXXXXXX, _____XXX, XXXXXXXX, XX______, _______X, XXXXXXXX, XXX_____, XXXXXXXX,
  XXXXXXXX, _____XXX, XXXXXXXX, X_______, ________, XXXXXXXX, XXX_____, _XXXXXXX,
  XXXXXXX_, _____XXX, XXXXXXXX, ________, ________, _XXXXXXX, XXXX____, _XXXXXXX,
  XXXXXXX_, ____XXXX, XXXXXXX_, ________, ________, __XXXXXX, XXXX____, _XXXXXXX,
  XXXXXXX_, ____XXXX, XXXXXX__, ________, ________, ___XXXXX, XXXX____, _XXXXXXX,
  XXXXXXX_, ____XXXX, XXXXX___, ________, ________, ____XXXX, XXXXX___, __XXXXXX,
  XXXXXXX_, ____XXXX, XXXX____, ________, ________, _____XXX, XXXXX___, __XXXXXX,
  XXXXXX__, ___XXXXX, XXXXXXXX, X_______, _______X, XXXXXXXX, XXXXX___, __XXXXXX,
  XXXXXX__, ___XXXXX, XXXXXXXX, X_______, _______X, XXXXXXXX, XXXXX___, __XXXXXX,
  XXXXXX__, ___XXXXX, XXXXXXXX, X_______, _______X, XXXXXXXX, XXXXX___, __XXXXXX,
  XXXXXX__, ___XXXXX, XXXXXXXX, X_______, _______X, XXXXXXXX, XXXXX___, __XXXXXX,
  XXXXXXX_, ____XXXX, XXXXXXXX, XX______, _______X, XXXXXXXX, XXXXX___, __XXXXXX,
  XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, __XXXXXX,
  XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXXXX,
  XXXXXXX_, ____XXXX, XXXXXXXX, X_______, _______X, XXXXXXXX, XXXX____, _XXXXXXX,
  XXXXXXX_, ____XXXX, XXXXXXXX, X_______, _______X, XXXXXXXX, XXXX____, _XXXXXXX,
  XXXXXXX_, _____XXX, XXXXXXXX, X_______, _______X, XXXXXXXX, XXX_____, _XXXXXXX,
  XXXXXXXX, _____XXX, XXXXXXXX, XX______, _______X, XXXXXXXX, XXX_____, XXXXXXXX,
  XXXXXXXX, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX,
  XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, XXXXXXXX,
  XXXXXXXX, X______X, XXXXXXXX, X_______, _______X, XXXXXXXX, X______X, XXXXXXXX,
  XXXXXXXX, XX_____X, XXXXXXXX, X_______, _______X, XXXXXXXX, X______X, XXXXXXXX,
  XXXXXXXX, XX______, XXXXXXXX, X_______, _______X, XXXXXXXX, ______XX, XXXXXXXX,
  XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, XXXXXXX_, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXX____, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ______XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmico_updating = {
  64, /* XSize */
  64, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_updating,  /* Pointer to picture data (indices) */
  &Palico_updating  /* Pointer to palette */
};

/* *** End of file *** */
