/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert V5.08.                                 *
*        Compiled Jan 13 2011, 12:35:22                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
**********************************************************************
*                                                                    *
* Source file: ico_alarm_stop                                        *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsico_alarm_stop[] = {
     0xFFFFFF,0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palico_alarm_stop = {
  2,   /* number of entries */
  0,    /* No transparency */
  &Colorsico_alarm_stop[0]
};

static GUI_CONST_STORAGE unsigned char acico_alarm_stop[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  XX______, ________, ________, ________, ________, ________, ________, ________,
  XXX_____, ________, ________, ____XXXX, XXXXX___, ________, ________, ________,
  _XXX____, ________, ________, _XXXXXXX, XXXXXXXX, ________, ________, ________,
  __XXX___, ________, _______X, XXXXXXXX, XXXXXXXX, XX______, ________, ________,
  ___XXX__, ________, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ____XXX_, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  _____XXX, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ______XX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  _______X, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, _XXX____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, __XXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ___XXX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ____XXX_, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, _____XXX, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ______XX, X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ______XX, XX______, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, _____XXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, _____XXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, _____XXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, ______XX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XX______, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, X______X, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XX______, XXXXXXXX, XXXX____, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXXX, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXX____, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _____XXX, XXXXX___, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXX__, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, XXXXXX__, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, XXXXXXX_, ________,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _XXXXXX_, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, __XXXXXX, ________,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, X_______,
  ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, X_______,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XX______,
  _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, XX______,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXX_____,
  ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _XX_____,
  ________, ________, ________, ________, ________, ________, _XX_____, ________,
  ________, ________, ________, ________, ________, ________, __XX____, ________,
  ________, ________, ________, ________, ________, ________, ___XX___, ________,
  ________, ________, ________, ________, ________, ________, ____XX__, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, _____XX_, ________,
  ________, ________, ________, XXXXXXXX, XXXXXXXX, X_______, ______XX, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, X_______, _______X, X_______,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, ________, ________, XX______,
  ________, ________, ________, __XXXXXX, XXXXXXXX, ________, ________, _XX_____,
  ________, ________, ________, __XXXXXX, XXXXXXX_, ________, ________, __XXX___,
  ________, ________, ________, ___XXXXX, XXXXXX__, ________, ________, ___XXX__,
  ________, ________, ________, _____XXX, XXXX____, ________, ________, ____XXX_,
  ________, ________, ________, ________, ________, ________, ________, _____XXX,
  ________, ________, ________, ________, ________, ________, ________, ______XX
};

GUI_CONST_STORAGE GUI_BITMAP bmico_alarm_stop = {
  64, /* XSize */
  64, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  acico_alarm_stop,  /* Pointer to picture data (indices) */
  &Palico_alarm_stop  /* Pointer to palette */
};

/* *** End of file *** */
