/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        µC/GUI-BitmapConvert-Demo V5.08.                            *
*        Compiled Jan 13 2011, 12:35:33                              *
*        (c) 2002-2010  Micrium, Inc.                                *
*        www.micrium.com                                             *
*                                                                    *
*        (c) 1998-2010  Segger Microcontroller GmbH & Co. KG *                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: MiVia_bootup                                          *
* Dimensions:  100 * 32                                              *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR ColorsMiVia_bootup[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE PalMiVia_bootup = {
  2,    /* number of entries */
  0,     /* No transparency */
  &ColorsMiVia_bootup[0]
};

static GUI_CONST_STORAGE unsigned char acMiVia_bootup[] = {
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  _____XXX, XXXXXXXX, _______X, XXXXXXXX, X_____XX, XXX___XX, XXXX____, ________, XXXXXX__, _XXXXX__, ________, ________, ________,
  _____XXX, XXXXXXXX, _______X, XXXXXXXX, X_____XX, XXX___XX, XXXX____, ________, XXXXXX__, _XXXXX__, ________, ________, ________,
  _____XXX, XXXXXXXX, ______XX, XXXXXXXX, X_____XX, XXX___XX, XXXX____, ________, XXXXXX__, _XXXXX__, ________, ________, ________,
  _____XXX, XXXXXXXX, ______XX, XXXXXXXX, X_____XX, XXX____X, XXXXX___, _______X, XXXXX___, _XXXXX__, ________, ________, ________,
  _____XXX, XX_XXXXX, X_____XX, XXX_XXXX, X_____XX, XXX____X, XXXXX___, _______X, XXXXX___, _XXXXX__, ________, ________, ________,
  _____XXX, XX__XXXX, X_____XX, XXX_XXXX, X_______, _______X, XXXXX___, _______X, XXXXX___, ________, ________, ________, ________,
  _____XXX, XX__XXXX, X____XXX, XX__XXXX, X_______, _______X, XXXXX___, _______X, XXXX____, ________, ________, ________, ________,
  _____XXX, XX__XXXX, X____XXX, XX__XXXX, X_______, ________, XXXXXX__, ______XX, XXXX____, ________, ____XXXX, XXXXXXX_, ________,
  _____XXX, XX__XXXX, XX___XXX, XX__XXXX, X_____XX, XXX_____, XXXXXX__, ______XX, XXXX____, _XXXXX__, __XXXXXX, XXXXXXXX, ________,
  _____XXX, XX___XXX, XX___XXX, X___XXXX, XX____XX, XXX_____, XXXXXX__, ______XX, XXXX____, _XXXXX__, __XXXXXX, XXXXXXXX, X_______,
  ____XXXX, XX___XXX, XX__XXXX, X___XXXX, XX____XX, XXX_____, _XXXXXX_, ______XX, XXX_____, _XXXXX__, __XXXXXX, __XXXXXX, X_______,
  ____XXXX, XX___XXX, XX__XXXX, X___XXXX, XX____XX, XXX_____, _XXXXXX_, _____XXX, XXX_____, _XXXXX__, ________, ____XXXX, X_______,
  ____XXXX, XX___XXX, XXX_XXXX, X____XXX, XX____XX, XXX_____, _XXXXXX_, _____XXX, XXX_____, _XXXXX__, ________, ____XXXX, X_______,
  ____XXXX, X_____XX, XXX_XXXX, _____XXX, XX____XX, XXX_____, __XXXXX_, _____XXX, XX______, _XXXXX__, ________, ____XXXX, X_______,
  ____XXXX, X_____XX, XXXXXXXX, _____XXX, XX____XX, XXX_____, __XXXXXX, ____XXXX, XX______, _XXXXX__, ______XX, XXXXXXXX, X_______,
  ____XXXX, X_____XX, XXXXXXXX, _____XXX, XX____XX, XXX_____, __XXXXXX, ____XXXX, XX______, _XXXXX__, ___XXXXX, XXXXXXXX, X_______,
  ____XXXX, X______X, XXXXXXX_, _____XXX, XX____XX, XXX_____, ___XXXXX, ____XXXX, X_______, _XXXXX__, __XXXXXX, XXXXXXXX, X_______,
  ____XXXX, X______X, XXXXXXX_, _____XXX, XX____XX, XXX_____, ___XXXXX, ____XXXX, X_______, _XXXXX__, _XXXXXXX, ____XXXX, X_______,
  ____XXXX, X______X, XXXXXXX_, _____XXX, XX____XX, XXX_____, ___XXXXX, X__XXXXX, X_______, _XXXXX__, _XXXXX__, ____XXXX, X_______,
  ____XXXX, X______X, XXXXXXX_, _____XXX, XX____XX, XXX_____, ____XXXX, X__XXXXX, X_______, _XXXXX__, _XXXXX__, ____XXXX, X_______,
  ____XXXX, X_______, XXXXXX__, _____XXX, XXX___XX, XXX_____, ____XXXX, X__XXXXX, ________, _XXXXX__, _XXXXX__, ____XXXX, X_______,
  ____XXXX, X_______, ________, _____XXX, XXX___XX, XXX_____, ____XXXX, XXXXXXXX, ________, _XXXXX__, _XXXXXX_, ____XXXX, X_______,
  ___XXXXX, X_______, ________, _____XXX, XXX___XX, XXX_____, _____XXX, XXXXXXXX, ________, _XXXXX__, _XXXXXXX, XXXXXXXX, X_______,
  ___XXXXX, X_______, ________, _____XXX, XXX___XX, XXX_____, _____XXX, XXXXXXX_, ________, _XXXXX__, __XXXXXX, XXXXXXXX, X_______,
  ___XXXXX, X_______, ________, _____XXX, XXX___XX, XXX_____, _____XXX, XXXXXXX_, ________, _XXXXX__, ___XXXXX, XXXXXXXX, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmMiVia_bootup = {
  100, /* XSize */
  32, /* YSize */
  13, /* BytesPerLine */
  1, /* BitsPerPixel */
  acMiVia_bootup,  /* Pointer to picture data (indices) */
  &PalMiVia_bootup  /* Pointer to palette */
};

/* *** End of file *** */
